# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - KundeApiTry5

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_c47cc38941b04570885e7a232cfdc330 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_85e044018b384d91b43d830236147885 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_c47cc38941b04570885e7a232cfdc330 }}/kunde-api:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'KundeApiTry5'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f0cf66a6ba68494e9c6750f85ce310bd }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_c47cc38941b04570885e7a232cfdc330 }}/kunde-api:${{ github.sha }}'